set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_BUILD_TYPE release)

if(NOT DEFINED ENV{WEBOS_CHAINLOAD_TOOLCHAIN})
    message(FATAL_ERROR "WEBOS_CHAINLOAD_TOOLCHAIN is not set")
endif()

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "$ENV{WEBOS_CHAINLOAD_TOOLCHAIN}")
